### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by pissypheous** [salgarcia666/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] 1. create an html skeleton
- [x] 2. create/styl the background
- [x] 2.  create/style the car
- [x] 3. make sure all the css and html that is not used is deleted
