### ISSUE TITLE
user can turn their car

### ISSUE THREAD

**Issue by pissypheous** [salgarcia666/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] 1. Create a simple data model that includes which way the car is facing, (north, south, east, or west).
- [x]  2.  Listen for 'keydown' events on the document.
- [x]  3. add functionality to those keydown events
- [x] 3. make sure all of the js that is not needed is deleted
