### ISSUE TITLE
user can stop their car

### ISSUE THREAD

**Issue by pissypheous** [salgarcia666/driving-game#4]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] listen for the space keydown event
- [x] add functionality to it
- [x] Add a boolean to your data model to indicate whether or not the car is started.
- [x] make sure all of the code that is not used is deleted 
- [x] make sure to add comments for readability
