### ISSUE TITLE
user can steer their car

### ISSUE THREAD

**Issue by pissypheous** [salgarcia666/driving-game#5]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [x] listen for keydown events
- [x] add functionality to those ketdown events
- [x] make sure that everything is working correctly and its not thorwing errors
- [x] delete all code that is not being used
